import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Moon, Sun, Play, Pause, X, Headphones, ArrowRight, SkipForward } from 'lucide-react';

const projects = [
  { name: 'nyx', subtitle: 'a controller for my Codex chaos.', tag: 'CURRENT OBSESSION', symbol: '☾', color: 'nyx', description: 'My own Codex controller. Using the tool somehow turned into building another tool around it. Anyway, we’re here now.', detail: 'I wanted a little more control over my Codex sessions. A reasonable person would have left it there. I made it a project. Still building, still adding “one last thing.”', stack: 'AI tooling · personal build · in progress', url: 'https://github.com/sidgupt12/nyx' },
  { name: 'maya', subtitle: 'giving scam detectors trust issues.', tag: 'TRUST ISSUES, SIMULATED', symbol: '◈', color: 'maya', description: 'What if scam detectors had a practice arena? Maya gives them fake payment journeys and looks for the stuff they miss. Built for the Mastercard Innovation Challenge 2026.', detail: 'Fake payments. Real detective work. It tests payment scams and swapped merchant QR codes, uses the misses to improve defenses, and checks that normal payments still get through. Everything happens in a controlled simulation; no real money gets involved.', stack: 'Python · Next.js · payment simulation · adversarial evaluation', url: 'https://github.com/sidgupt12/maya', live: 'https://maya.siddhant.cc/' },
  { name: 'ForgetAI', subtitle: 'for everything I swear I’ll remember.', tag: 'MY BRAIN’S BACKUP', symbol: '✳︎', color: 'forget', description: 'My saved folder was becoming a digital landfill. So I built a place for PDFs, tweets and notes that lets me ask where that one thing went.', detail: 'It breaks saved material into searchable pieces and finds it again when I ask a question. Basically, a second brain for the first brain that said “I’ll remember this.”', stack: 'Go · Next.js · MongoDB · Redis · Pinecone', url: 'https://github.com/sidgupt12/forgetai', live: 'https://forgetai.siddhant.cc/' },
  { name: 'GitHub MCP', subtitle: 'less tab switching. allegedly.', tag: 'TAB REDUCTION ATTEMPT', symbol: '↳', color: 'mcp', description: 'Made my assistant deal with GitHub so I could stop opening it every twelve seconds. A small win for the tab situation.', detail: 'Ten tools for repos, branches, files and pull requests, wrapped in a TypeScript MCP server. It’s on npm. The tabs are still open, but now that’s a personal choice.', stack: 'TypeScript · Node.js · Octokit · Zod', url: 'https://github.com/sidgupt12/git-mcp-server', live: 'https://www.npmjs.com/package/claude-github-mcp' },
];
const tracks = [ {title:'Victory (Instrumental)',artist:'Lakshya',file:'victory-instrumental'}, {title:'Purple Rain',artist:'Prince',file:'purple-rain'}, {title:'Shivam',artist:'Baahubali 2',file:'shivam'}, {title:'Yellow (Acoustic)',artist:'Coldplay',file:'yellow'} ];
const time = (n:number) => `${Math.floor(n / 60)}:${String(Math.floor(n % 60)).padStart(2,'0')}`;
function readPreference(key:string) { try { return localStorage.getItem(key); } catch { return null; } }
export default function Index() {
 const [dark,setDark] = useState(() => readPreference('sid-theme') !== 'light');
 const [curtain,setCurtain] = useState(true);
 const [selected,setSelected] = useState<number|null>(null);
 const dialog = useRef<HTMLDialogElement>(null);
 const cvDialog = useRef<HTMLDialogElement>(null);
 const stealthDialog = useRef<HTMLDialogElement>(null);
 const rickDialog = useRef<HTMLDialogElement>(null);
 const [rickrolled,setRickrolled] = useState(false);
 const [rickSource,setRickSource] = useState<"dopamine"|"footer">("dopamine");
 const [track,setTrack] = useState(0); const [playing,setPlaying]=useState(false); const [position,setPosition]=useState(0); const [duration,setDuration]=useState(0); const [error,setError]=useState(''); const audio=useRef<HTMLAudioElement>(null);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';try{localStorage.setItem('sid-theme',dark?'dark':'light');}catch{/* optional preference */}},[dark]);
 useEffect(()=>{if(selected!==null)dialog.current?.showModal();},[selected]);
 useEffect(()=>{if(!curtain)return;const id=window.setTimeout(()=>{setCurtain(false);},2600);return()=>clearTimeout(id)},[curtain]);
 const enter=()=>{setCurtain(false);};
 const choose=(i:number)=>{setTrack(i);setPosition(0);setDuration(0);setError('');setPlaying(false);};
 const toggle=async()=>{if(!audio.current)return;if(playing)audio.current.pause();else try{await audio.current.play();setError('');}catch{setError('Couldn’t play this track. Try again.');}};
 const project=selected===null?null:projects[selected];
 return <>
 {curtain&&<div className="curtain"><span className="eyebrow">a very unnecessary dramatic entrance</span><div className="curtain-mark">sid<span>.</span></div><img className="curtain-gif" src="/images/saitama-ok.gif" alt="Saitama giving an unimpressed OK"/><p>this entrance had a bigger budget in my head.</p><button onClick={enter}>skip the lore <ArrowRight size={16}/></button><div className="curtain-line"/></div>}
 <div className="site-shell" ref={node=>{if(node)node.inert=curtain;}}>
 <header><a href="#" className="wordmark" aria-label="Sid home">s.</a><nav><a href="#builds">builds</a><a href="#music">on repeat</a><button className="theme-toggle" onClick={()=>setDark(!dark)} aria-label={`Switch to ${dark?'light':'dark'} mode`}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></nav></header><div className="theme-aside" role="status">{!dark&&<span>light mode? okay, sunshine. i’m awake now.</span>}</div>
 <main>
 <section className="hero"><div className="eyebrow"><span className="status-dot"/> somewhere between a commit & an episode</div><div className="hero-title"><div className="hero-name"><h1>sid<span>.</span></h1><p className="name-note">it’s siddhant. sid just had better branding.</p></div><figure className="batman"><img src="/images/batman.gif" alt="Batman at the Batcomputer"/><figcaption>actual footage of me debugging ↗</figcaption></figure><span className="hero-spark" aria-hidden="true">✳︎</span></div><h2>backend engineer.<br/>“quick side project” enthusiast.<br/><span>several tabs past a reasonable bedtime.</span></h2><p className="hero-copy">the side quests are getting suspiciously ambitious.</p><div className="hero-links"><a href="https://github.com/sidgupt12" target="_blank" rel="noreferrer">github <ArrowUpRight size={16}/></a><a href="mailto:sidgupt12@gmail.com">say hey <ArrowUpRight size={16}/></a><button className="cv-link" onClick={()=>cvDialog.current?.showModal()}>resume <ArrowUpRight size={16}/></button><button className="cv-link dopamine-link" onClick={()=>{setRickSource("dopamine");setRickrolled(true);rickDialog.current?.showModal();}}><span>free dopamine</span><span className="dopamine-cue">click me <ArrowUpRight size={14}/></span></button></div></section>
 <section id="builds" className="builds"><div className="section-heading"><h2><span>01 /</span> the side quests</h2><span>“i could build that” — me, regrettably</span></div><button className="featured-project" onClick={()=>setSelected(0)}><div className="project-art nyx"><span className="art-label">NYX / AFTER HOURS</span><span className="moon-art">☾</span><span className="art-bottom">a little control over the chaos.</span></div><div className="featured-copy"><span className="eyebrow"><span className="status-dot"/> currently building</span><h3>nyx <ArrowUpRight/></h3><p>my own Codex controller.</p><p className="muted">using the tool somehow turned into building another tool around it.</p><span className="project-open">the plot thickens <ArrowRight size={17}/></span></div></button><div className="project-grid">{projects.slice(1).map((p,i)=><button className="small-project" key={p.name} onClick={()=>setSelected(i+1)}><div className={`project-art ${p.color}`}><span className="art-label">{p.tag}</span><span className="art-symbol">{p.symbol}</span></div><h3>{p.name}<ArrowUpRight size={18}/></h3><p>{p.subtitle}</p></button>)}</div></section>
 <section className="about"><div className="section-heading"><h2><span>02 /</span> a little lore</h2><span>the civilian identity</span></div><div className="about-grid"><div><h3>Clark Kent hours.<br/><span>Bruce Wayne sleep schedule.</span></h3><p>software engineer at <b>Info Edge</b>. i make things work behind the scenes, then go home and make more things. i like knowing how stuff works. unfortunately, that keeps turning into a commitment.</p><div className="company-list"><a href="https://www.naukri.com/" target="_blank" rel="noreferrer"><img src="/images/naukri.png" alt="Naukri.com logo"/><span>Info Edge / Naukri<small>the day job · now</small></span><ArrowUpRight size={16}/></a><a href="https://www.codingjr.online/" target="_blank" rel="noreferrer"><img src="/images/codingjr.png" alt="Coding Jr logo"/><span>Coding Jr<small>backend adventures · 2025</small></span><ArrowUpRight size={16}/></a><button className="stealth-row" onClick={()=>stealthDialog.current?.showModal()} title="never saw the light of day. coffee for the lore?"><img className="stealth-image" src="/images/stealth.png" alt="Stealth startup emblem"/><span>Stealth startup<small>didn’t make it out of stealth · 2025</small></span><ArrowUpRight size={16}/></button></div></div><aside className="training"><div className="training-top"><span className="eyebrow">training arc</span><span>↗</span></div><img loading="lazy" src="/images/ed.gif" alt="Ed from Cowboy Bebop hacking"/><h3>the math has hands.</h3><p>learning how to build a model from scratch. haven’t built one yet. just very invested in what’s going on in there.</p><div className="stack">Go / Java / Python / TypeScript<br/>Redis / Docker / too much coffee</div></aside></div></section>
 <section id="music" className="music"><div className="section-heading"><h2><span>03 /</span> the soundtrack</h2><Headphones size={18}/></div><p className="music-caption">when everything else gets boring, these go on repeat.<br/>suddenly the grocery run has a season finale soundtrack.</p><div className="music-layout"><div className="now-playing"><span className="eyebrow">{playing?'on repeat right now':'press play. stay a while.'}</span><h3>{tracks[track].title}</h3><p>{tracks[track].artist}</p><div className="transport"><button onClick={toggle} className="play-button" aria-label={playing?'Pause':'Play'}>{playing?<Pause size={20}/>:<Play size={20}/>}</button><input aria-label="Seek track" type="range" min="0" max={duration||0} value={position} onChange={e=>{const n=Number(e.target.value);if(audio.current)audio.current.currentTime=n;setPosition(n)}}/><button className="icon-button" aria-label="Next track" onClick={()=>choose((track+1)%tracks.length)}><SkipForward size={18}/></button></div><div className="time"><span>{time(position)}</span><span>{time(duration)}</span></div><p role="status" className="audio-error">{error}</p><audio ref={audio} src={`/audio/music/${tracks[track].file}.m4a`} preload="metadata" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onTimeUpdate={e=>setPosition(e.currentTarget.currentTime)} onLoadedMetadata={e=>setDuration(Number.isFinite(e.currentTarget.duration)?e.currentTarget.duration:0)} onError={()=>setError('Track unavailable. Try another one.')}/></div><div className="track-list">{tracks.map((t,i)=><button key={t.file} onClick={()=>choose(i)} aria-pressed={track===i}><span>{track===i?'♫':`0${i+1}`}</span><span>{t.title}<small>{t.artist}</small></span>{track===i&&<span className="track-dot"/>}</button>)}</div></div></section>
 <section className="activity"><div className="section-heading"><h2><span>04 /</span> still shipping</h2><a href="https://github.com/sidgupt12" target="_blank" rel="noreferrer">github <ArrowUpRight size={14}/></a></div><p>most day-to-day commits live on my org’s GitLab.<br/>this is where the late-night experiments go.</p><a href="https://github.com/sidgupt12" target="_blank" rel="noreferrer" className="contribution-map"><img loading="lazy" src="https://ghchart.rshah.org/9b91df/sidgupt12" alt="Siddhant’s GitHub contribution calendar"/></a><div className="commit-reaction"><div><span className="eyebrow">↑ the graph</span><p>different remote. still shipping.<br/><span className="muted">“one last commit” was three hours ago.</span></p></div><figure><img loading="lazy" src="/images/commit-mood.gif" width="110" height="82" alt="Anime character slumped over a desk in front of a computer"/><figcaption>the person responsible ↑</figcaption></figure></div></section>
 </main><footer><div><button className="footer-hello" onClick={()=>{setRickSource("footer");setRickrolled(true);rickDialog.current?.showModal();}}>got a side quest? <ArrowUpRight/></button><p>see you, space cowboy.</p></div><figure className="lantern-cameo"><img loading="lazy" src="/images/green-lantern.gif" width="100" height="58" alt="Green Lantern John Stewart saying let’s go"/><figcaption>willpower: yes. bedtime: no.</figcaption></figure><div className="footer-links"><a href="https://x.com/s0lomate" target="_blank" rel="noreferrer">x ↗</a><a href="https://www.linkedin.com/in/siddhantgupta12" target="_blank" rel="noreferrer">linkedin ↗</a><a href="https://leetcode.com/u/sidgupt12/" target="_blank" rel="noreferrer">leetcode ↗</a><a href="mailto:sidgupt12@gmail.com">email ↗</a></div></footer><div className="endnote"><span>© {new Date().getFullYear()} sid.</span><span>made between episodes ☾</span></div>
 </div>
 <dialog ref={stealthDialog} className="project-dialog stealth-dialog" onClick={e=>{if(e.target===e.currentTarget)stealthDialog.current?.close();}}><div className="window-bar"><span><i/><i/><i/></span><span>stealth / unreleased episode</span><button aria-label="Close stealth startup story" onClick={()=>stealthDialog.current?.close()}><X size={18}/></button></div><div className="dialog-copy"><span className="eyebrow">the lost pilot episode · 2025</span><h2>so stealth, it never<br/>saw the light of day.</h2><p>some side quests don’t get a season two.</p><p className="muted">this one’s a coffee story. grab a cup and i’ll tell you the lore.</p><div className="hero-links"><a href="https://www.instagram.com/sidgupt12/" target="_blank" rel="noreferrer">coffee + lore? <ArrowUpRight size={16}/></a></div></div></dialog>
 <dialog ref={rickDialog} className="project-dialog rick-dialog" onClose={()=>setRickrolled(false)} onClick={e=>{if(e.target===e.currentTarget)rickDialog.current?.close();}}><div className="window-bar"><span><i/><i/><i/></span><span>totally-important-file.mp4</span><button aria-label="Close Rickroll" onClick={()=>rickDialog.current?.close()}><X size={18}/></button></div>{rickrolled&&<div className="rick-content"><span className="eyebrow">side quest successfully failed</span><h2>{rickSource==="footer"?<>rickrolled here too?<br/>no way<span> ♡</span></>:<>bro fell for<br/>the side quest<span> ♡</span></>}</h2><p>{rickSource==="footer"?"haha. the side quest was Rick all along.":"you’ve been rickrolled. in this economy."}</p><div className="rick-video"><iframe src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1&playsinline=1&rel=0" title="Rick Astley — Never Gonna Give You Up" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen/></div><div className="rick-footnote"><span>no sound? hit play. commit to the bit.</span><a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank" rel="noreferrer">watch on youtube ↗</a></div></div>}</dialog>
 <dialog ref={cvDialog} className="project-dialog cv-dialog" onClick={e=>{if(e.target===e.currentTarget)cvDialog.current?.close();}}><div className="window-bar"><span><i/><i/><i/></span><span>sid / the official lore</span><button aria-label="Close resume" onClick={()=>cvDialog.current?.close()}><X size={18}/></button></div><div className="cv-actions"><span>the slightly more employable version of me.</span><a href="/Siddhant_CV.pdf" download>download resume ↓</a><a href="/Siddhant_CV.pdf" target="_blank" rel="noreferrer">open PDF ↗</a></div><object data="/Siddhant_CV.pdf" type="application/pdf" aria-label="Siddhant Gupta’s resume"><p>Your browser doesn’t support an embedded PDF. <a href="/Siddhant_CV.pdf" target="_blank" rel="noreferrer">Open the resume here ↗</a></p></object></dialog>
 <dialog ref={dialog} className="project-dialog" onClose={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}}>{project&&<><div className="window-bar"><span><i/><i/><i/></span><span>{project.name.toLowerCase()} / the lore</span><button aria-label="Close project details" onClick={()=>dialog.current?.close()}><X size={18}/></button></div><div className={`dialog-art project-art ${project.color}`}><span className="art-symbol">{project.symbol}</span></div><div className="dialog-copy"><span className="eyebrow">{project.tag}</span><h2>{project.name}</h2><p>{project.description}</p><p className="muted">{project.detail}</p><p className="stack">{project.stack}</p><div className="hero-links"><a href={project.url} target="_blank" rel="noreferrer">follow the build <ArrowUpRight size={16}/></a>{project.live&&<a href={project.live} target="_blank" rel="noreferrer">check it out <ArrowUpRight size={16}/></a>}</div></div></>}</dialog>
 </>;
}
